Responsividade login pages
MuriloZague/receitalhada pull request #6
Opened 2024-10-26 23:54 UTC by MuriloZague

responsividade adicionada para dispositivos abaixo de 450px nas telas de login e cadastro.

2024-10-26 23:56 UTC, MuriloZague commented
teste antes do merge "https://receitalhada-git-responsividade-lo-972529-murilozagues-projects.vercel.app/?_vercel_share=iGsyRvqXvi4ATy3DIGebJ7GyvIXCKa1G"

2024-10-27 22:00 UTC, jpmoncao commented on frontend/tailwind.config.js
Eu entendi o motivo de ter criado um tamanho de tela personalizado, mas talvez eu cogitaria usar o `sm:` padrão do tailwind. 
Mesmo assim, não creio que precisa de mudanças não, fique bom.

2024-10-27 22:03 UTC, jpmoncao requested changes
1. Eu percebi que também será necessário ajustes nas telas médias, lancei um card sobre isso.
2. Não esqueça de fazer um card para os PR's, acho que fica mais organizado o front separado dos de design

2024-10-27 22:03 UTC, jpmoncao commented on frontend/src/components/ListRevenues.tsx
Eu acredito que é interessante mostrar os anúncios também nas telas mobile. Apesar de poluir, os maiores acessos virão de lá, então precisamos gerar receitas assim também.
Sugestão:
![image](https://github.com/user-attachments/assets/c411f3cd-2b05-4039-ae3f-117ed109e6af)

2024-10-27 22:04 UTC, MuriloZague commented on frontend/tailwind.config.js
O tailwind foi desenvolvido com o objetivo do mobile first, usando o `sm:` ele faria de tela de 640px **acima** e não o contrário 🙌🙌

2024-10-28 15:17 UTC, MuriloZague commented
tela para tablets e dispositivos médio adicionada 
_lembrete para mim mesmo, nunca mais fazer mobile last 😢_

2024-10-28 16:05 UTC, jpmoncao requested changes

2024-10-28 16:05 UTC, jpmoncao commented on frontend/src/components/Search.tsx
![image](https://github.com/user-attachments/assets/0a72f15a-e274-468c-9182-529541ff4f5d)
Eu ainda achei o input de pesquisa muito grande 😢 , acho que daria para deixar bem menor. 
(Tela do iPad mini)

2024-10-28 16:20 UTC, MuriloZague commented on frontend/src/components/Search.tsx
corrigido🙌🙌

2024-10-28 16:26 UTC, jpmoncao commented
Perfeito rei, agora é só nós lembrarmos do mobile first. 
![VapoJaEraGIF](https://github.com/user-attachments/assets/e87e4e07-fb12-4491-9aaf-69e0b4da925b)

2024-10-28 16:26 UTC, merged